import green from "@material-ui/core/colors/green";

const styles = (theme) => ({
  root: {
    flexGrow: 1,
    height: "100%",
    marginTop: "-120px",
    marginBottom: "-990px",
    marginRight: "-8px",
    marginLeft: "-8px",
  },
  loginPage: {
    width: "100%",
    padding: "0px",
    margin: "0",
  },
  login: {
    marginBottom: "-890px",
  },
  leftImage: {
    position: "absolute",
    position: " relative",
    width: "110%",
    height: "110%",

    padding: "0px",
    margin: "-20px 0 0 0",
  },
  leftImage1: {
    position: " relative",
    width: "100%",
    marginTop: "-900px",
    marginBottom: "100px",
    marginLeft: "-40px",
    padding: "0px",
    margin: "70px 0 0 0",
  },
  leftContent: {
    paddingBottom: "-990px",
    //background": "transparent linear-gradient(142deg, #74329C 0%, #3D358F 100%) 0% 0% no-repeat padding-box",
    backgroundImage: "url(../images/Bg.png)",
    backgroundPosition: "right top",
    backgroundRepeat: "no-repeat",
    // backgroundColor: "#f5f6fa",
    opacity: "1",
    textAlign: "center",
    // position: "relative",
  },
  PoweredBy: {
    width: "100%",
    position: "absolute",
    bottom: "15px",
    color: "#ffffff",
    opacity: "0.39",
    fontSize: "16px",
    textAlign: "center",
  },
  rightContent: {
    paddingBottom: "70px",
    textAlign: "center",
    // background: "#f5f6fa 0% 0% ",
    opacity: "1",
    backgroundRepeat: "no-repeat",
    // position: "relative",
  },
  rightContent1: {
    marginTop: "50px",
  },
  keralaPoliceLogo: {
    width: "168px",
    padding: "0",
    margin: "70px 0 0 0",
  },
  h1: {
    color: "#3d358f",
    textTransform: "uppercase",
    opacity: "1",
    letterSpacing: "0px",
    fontSize: "46px",
    margin: "10px 0 0 0",
    fontWeight: "",
  },
  h2: {
    letterSpacing: "0px",
    color: "#3d358f",
    textTransform: "uppercase",
    opacity: "1",
    fontSize: "24px",
    margin: "0",
    fontWeight: "normal",
  },
  TextField: {
    width: "100%",
    height: "50px",
    padding: "0",
    paddingBottom: "5px",
    margin: "0 0 20px 0",
    background: "#ffffff 0% 0% ",
    backgroundRepeat: "no-repeat",
    borderColor: "#c4ccdc",
    borderRadius: "8px",
    color: "#98a1b2",
    opacity: "1",
  },
  form1: {
    padding: "0",
    margin: "30px 0 0 0",
  },
  marginTOP: {
    marginTop: "35px",

    margin: "0 0 20px 0",
    width: "100%",
    height: "54px",
    background: "#3d358f 0% 0%",
    backgroundRepeat: "no-repeat",
    borderRadius: "8px",
    opacity: "1",
    letterSpacing: "0px",
    color: "#ffffff",
    fontSize: "16px",
    textTransform: "none",
  },
  dontHaveAccount: {
    letterSpacing: "0px",
    color: "#98a1b2 ",
    opacity: "1",
    fontSize: "12px",
    textDecoration: "none",
    marginLeft: "-150px",
  },
  dontHaveAccount1: {
    letterSpacing: "0px",
    color: "#3D358F ",
    opacity: "1",
    fontSize: "12px",
    textDecoration: "none",
    marginLeft: "190px",

    marginTop: "-17px",
  },
  powerdByText: {
    marginTop: "50px",
    letterSpacing: "0px",
    color: "#98a1b2",
    opacity: "1",
    fontSize: "14px",
  },
  ultsLogo: {
    padding: "0 0 0 10px",
    margin: "0",
    width: "56px",
  },

  a: {
    letterSpacing: "0px",
    color: "#3d358f ",
    opacity: "1",
    fontSize: "14px",
    textDecoration: "none",
  },
});

export default styles;
