export const styles = (theme) => ({
  dashboardContent: {
    marginTop: "50px",
  },
  h6: {
    fontSize: "1.25rem",
    letterSpacing: "0px",
    color: "#3d358f",
    opacity: "1",
    marginLeft: "27px",
    fontWeight: "500",
  },
  SearchIcon: {
    color: "#C4CCDC",
  },
  cctnResults: {
    padding: "19px",
    margin: "0px",
    marginTop: "-20px",
  },
  clearAllBtn: {
    margin: "20px 0 0 27px",
    background: "#dce0e7",
    borderRadius: "4px",
    opacity: "1",
    color: "#949dae",
    fontSize: "small",
    textTransform: "none",
    width: "10%",
  },
  SearchBtn: {
    margin: "20px 0 0 27px",
    background: "#3d358f",
    borderRadius: "4px",
    opacity: "1",
    color: "#ffffff",
    fontSize: "small",
    textTransform: "none",
    width: "10%",
  },

  cctnsearchBox: {
    padding: "20px",
    margin: "10px 0",

    width: "maxcontent",
    textAlign: "Left",
    marginBottom: "20px",
    marginRight: "auto",

    background: "#eceff4",
    borderRadius: "5px",
    // borderRadius: "-800px",
    // borderWidth: "90%",
    // strokeWidth: "30",
  },
  clearAllBtn: {
    margin: "-100px 0 0 10px",
    background: "#dce0e7",
    borderRadius: "4px",
    opacity: "1",
    color: "#949dae",
    fontSize: "small",
    textTransform: "none",
    width: "10%",
  },
  SearchBtn: {
    margin: "-100px 0 0 10px",
    background: "#3d358f",
    borderRadius: "4px",
    opacity: "1",
    color: "#ffffff",
    fontSize: "small",
    textTransform: "none",
    width: "10%",
  },
  passportRequestBg: {
    marginBottom: "20px",
    padding: "20px",
    background: "#eceff5",
    borderRadius: "8px",
  },
  folderIcon: {
    marginRight: "10px",
    color: "white",
    height: "30px",
    width: "30px",
    padding: "5px",
    background: "#74329c 0% 0% no-repeat padding-box",
    opacity: "1",
    borderRadius: "50%",
  },
  heading: {
    letterSpacing: "0px",
    color: "#98a1b2",
    opacity: "1",
    fontSize: "14px",
    marginTop: "6px",
  },
  completedGreen: {
    color: "#65bc6b",
    margin: "6px 5px 0 auto",
  },
  subHeading: {
    letterSpacing: "0px",
    color: "#98a1b2",
    opacity: "1",
    fontSize: "14px",
    backgroundSize: "1px solid #98a1b2",
    marginTop: "6px",
  },
  avatarName: {
    color: "#98a1b2",
    opacity: "1",
    fontSize: "small",
    margin: "10px",
  },
  ContentsText: {
    letterSpacing: " 0px",
    color: "#98a1b2",
    opacity: "1",
    fontSize: "14px",
    // float: "left",
    // marginRight: "10px",
  },
  ContentsText1: {
    letterSpacing: " 0px",
    color: "#98a1b2",
    opacity: "1",
    fontSize: "14px",
    float: "right",
    marginRight: "10px",
  },
  button: {
    float: "left",
  },
  button1: {
    background: "#3d358f ",
    opacity: "1",
    letterSpacing: "0px",
    color: "#ffffff",
    fontSize: "16px",
    textTransform: "none",
  },
});
